spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: kaicidummy@gmail.com
    password: pttv dqut zjmh smji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#enabling debug and trace as it is not default enabled in Slf4j
logging:
  level:
    net:
      tothenew:
        journalApp: DEBUG

weather:
  api:
    key: 0fd82e643c0826808b8a4632afd80952

