spring:
  data:
    mongodb:
      uri: mongodb+srv://kaisilious:J36LPaNgKGlhrfvi@journal.gnjq81h.mongodb.net/?retryWrites=true&w=majority&appName=Journal
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
#  servlet:
#    context-path: /journal


