spring:
  profiles:
    active: dev

#enabling debug and trace as it is not default enabled in Slf4j
logging:
  level:
    net:
      tothenew:
        journalApp: DEBUG

weather:
  api:
    key: 0fd82e643c0826808b8a4632afd80952